apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.1  # More stable version
  dataDirHostPath: /var/lib/rook
  mon:
    count: 2
    allowMultiplePerNode: true
  mgr:
    count: 1
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: gingmachine
        devices:
          - name: "/dev/sdb"  # Use the unused disk
      - name: ging-laptop.nick-knows.net
        devices:
          - name: /dev/loop37  # Will be something like /dev/loop37
      - name: gingworker
        devices:
          - name: /dev/loop0 # Will be something like /dev/loop7