apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: cephfs
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1  # For single-node Ceph
  dataPools:
    - name: replicated
      replicated:
        size: 1  # For single-node Ceph
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: false