apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.1
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  mgr:
    count: 1
  dashboard:
    enabled: true
  storage:
    useAllNodes: false  # Must be false to specify nodes manually
    useAllDevices: false
    nodes:
      - name: gingmachine  # Exact hostname
        directories:
          - path: "/var/lib/ceph-storage"  # Use path instead of name
      - name: ging-laptop.nick-knows.net  # Exact hostname
        directories:
          - path: "/var/lib/ceph-storage"  # Use path instead of name
      - name: gingworker  # Exact hostname
        directories:
          - path: "/var/lib/ceph-storage"  # Use path instead of name