apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: osd  # Change from 'host' to 'osd' for directory-based OSDs
  replicated:
    size: 1 