apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  failureDomain: osd  # This can be 'host' or 'osd' depending on your setup
  replicated:
    size: 1