{{- if (index .Values "codeserver" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codeserver
  namespace: argo
spec:
  destination:
    namespace: codeserver
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: ci/helm-chart/
      repoURL: {{ (index .Values "codeserver" "source" "repoURL") }}
      targetRevision: {{ (index .Values "codeserver" "source" "targetRevision") }}
      helm:
        valueFiles: 
          - $sourceRepo/values/codeserver-values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}