{{- if .Values.apps.ctsmjhub.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ctsm-jhub
  namespace: argocd
spec:
  destination:
    namespace: ctsm
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://hub.jupyter.org/helm-chart
      chart: jupyterhub
      targetRevision: {{ .Values.apps.ctsmjhub.chartVersion}}
      helm:
        valueFiles: 
          - $values/values/ctsm-jhub.yaml
    - repoURL: https://github.com/Gin-G/argo-k8s-stuff
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    automated:
      prune: true
      selfHeal: true
{{- end }}