{{- if .Values.minio.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
spec:
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://charts.min.io/
      chart: minio
      targetRevision: {{ .Values.minio.chartVersion}}
      helm:
        valueFiles: 
          - $values/values/minio.yaml
    - repoURL: https://github.com/Gin-G/argo-k8s-stuff
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Prune=true
    automated:
      prune: true
      selfHeal: true
{{- end }}