{{- if (index .Values "mvderby" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mvderby
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mvderby
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: k8s/
    repoURL: {{ (index .Values "mvderby" "source" "repoURL") }}
    targetRevision: {{ (index .Values "mvderby" "source" "targetRevision") }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
