{{- if (index .Values "notebook-web" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-web
  namespace: argo
spec:
  destination:
    namespace: notebook-web
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: chart/
      repoURL: {{ (index .Values "notebook-web" "source" "repoURL") }}
      targetRevision: {{ (index .Values "notebook-web" "source" "targetRevision") }}
      helm:
        valueFiles: 
          - $sourceRepo/values/notebook-web-values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/notebook-web/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}