{{- if (index .Values "skitunes" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skitunes
  namespace: argo
spec:
  destination:
    namespace: skitunes
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: helm-chart/
      repoURL: {{ (index .Values "skitunes" "source" "repoURL") }}
      targetRevision: {{ (index .Values "skitunes" "source" "targetRevision") }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/skitunes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}