dashboard:
  enabled: true
  ingress:
    enabled: true
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: websecure,
      traefik.ingress.kubernetes.io/router.tls: "true",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: traefik,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    ingressClassName: "traefik"
    hosts: ["argorollouts.ging.nickknows.net"]
    tls:
    - secretName: argorollouts.ging.nickknows.net-tls
      hosts:
        - argorollouts.ging.nickknows.net
