grafana:
  ingress:
    enabled: true
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: websecure,
      traefik.ingress.kubernetes.io/router.tls: "true",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: traefik,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    hosts: 
      - grafana.ging.nickknows.net
    ingressClassName: traefik
    tls:
    - secretName: grafana.ging.nickknows.net-tls
      hosts:
        - grafana.ging.nickknows.net
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path

loki:
  # Configure log collection
  serviceMonitor:
    enabled: true
  ingester:
    persistence:
      enabled: true
      claims:
        - name: loki-ingester
          storageClassName: local-path
          size: 10Gi
          annotations: {
            volume.kubernetes.io/hostname: "gingmachine"
          }