grafana:
  ingress:
    enabled: true
    annotations: {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/ssl-passthrough: "false",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: nginx,
      external-dns.alpha.kubernetes.io/target: "75c20a42-2dd1-4297-8a51-3aefbcb3f004.cfargotunnel.com"
    }
    hosts: 
      - grafana.nickknows.net
    ingressClassName: nginx
    tls:
    - secretName: grafana.nickknows.net-tls
      hosts:
        - grafana.nickknows.net
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path

loki:
  enabled: true

mimir:
  enable: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path

tempo:
  enabled: false
