grafana:
  ingress:
    enabled: true
    annotations: {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/ssl-passthrough: "false",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: nginx,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    hosts: 
      - grafana.ging.nickknows.net
    ingressClassName: nginx
    tls:
    - secretName: grafana.ging.nickknows.net-tls
      hosts:
        - grafana.ging.nickknows.net
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path

loki:
  enable: false
  # Configure log collection
  #serviceMonitor:
  #  enabled: true
  #ingester:
  #  persistence:
  #    enabled: true
  #    claims:
  #      - name: loki-ingester
  #        storageClassName: local-path
  #        size: 10Gi
  #        annotations: {
  #          volume.kubernetes.io/selected-node: "gingmachine"
  #        }

mimir:
  enable: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path