grafana:
  ingress:
    enabled: true
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: websecure,
      traefik.ingress.kubernetes.io/router.tls: "true",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: traefik,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    hosts: 
      - grafana.ging.nickknows.net
    ingressClassName: traefik
    tls:
    - secretName: grafana.ging.nickknows.net-tls
      hosts:
        - grafana.ging.nickknows.net
  persistence:
    enabled: true
    type: pvc
    storageClassName: local-path

loki:
  # Enable log collection from various sources
  config:
    chunk_store_config:
      max_look_back_period: 336h  # 14 days of logs
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h

  # Configure log collection
  serviceMonitor:
    enabled: true

  # Configure log collection from various sources
  schedulerConfig:
    # Collect logs from all namespaces
    log_level: info
    
  # Ensure you have enough storage for logs
  persistence:
    enabled: true
    storageClassName: local-path
    size: 10Gi

