ingress:
  enabled: true
  annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
      kubernetes.io/ingress-class: nginx
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
  ingressClassName: nginx
  path: /
  hosts: 
    - minio.nickknows.net
  tls:
    - secretName: minio-tls
      hosts:
        - minio.nickknows.net
persistence:
  enabled: true
  storageClass: "rook-cephfs"
  volumeName: "minio-pvc"
  accessMode: ReadWriteMany
  size: 10Gi
