prometheus:
  ingress:
    enabled: true
    annotations: {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/ssl-passthrough: "false",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: nginx,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    ingressClassName: "nginx"
    hosts: ["prometheus.ging.nickknows.net"]
    tls:
    - secretName: prometheus.ging.nickknows.net-tls
      hosts:
        - prometheus.ging.nickknows.net
  prometheusSpec:
    remoteWrite:
      - url: http://10.43.50.204
    additionalScrapeConfigs: 
      - job_name: 'prometheus'
        honor_labels: true
        static_configs:
        - targets: ['10.43.50.204']