prometheus:
  ingress:
    enabled: true
    annotations: {
      nginx.ingress.kubernetes.io/ssl-redirect: "true",
      nginx.ingress.kubernetes.io/ssl-passthrough: "false",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: nginx,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    ingressClassName: "nginx"
    hosts: ["prometheus.ging.nickknows.net"]
    tls:
    - secretName: prometheus.ging.nickknows.net-tls
      hosts:
        - prometheus.ging.nickknows.net
  prometheusSpec:
    remoteWrite:
      - url: http://lgtm-mimir-distributor.lgtm.svc.cluster.local:8080/api/v1/push
        name: mimir
        remote_timeout: 30s
        queue_config:
          capacity: 2500
          max_shards: 200
          min_shards: 1
          max_samples_per_send: 500
#    additionalScrapeConfigs: 
#      - job_name: 'prometheus'
#        honor_labels: true
#        static_configs:
#        - targets: ['10.43.50.204']