prometheus:
  ingress:
    enabled: true
    annotations: {
      traefik.ingress.kubernetes.io/router.entrypoints: websecure,
      traefik.ingress.kubernetes.io/router.tls: "true",
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare",
      kubernetes.io/ingress-class: traefik,
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
    }
    ingressClassName: "traefik"
    hosts: ["prometheus.ging.nickknows.net"]
    tls:
    - secretName: prometheus.ging.nickknows.net-tls
      hosts:
        - prometheus.ging.nickknows.net
