deployment:
  kind: DaemonSet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

providers:
  kubernetesIngress:
    enabled: true
  kubernetesIngressNGINX:
    enabled: true
    ingressClass: "nginx"

service:
  enabled: true
  type: LoadBalancer
  externalTrafficPolicy: Local