deployment:
  kind: DaemonSet
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  enabled: false