apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: externaldns
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: OPENBAO_TOKEN
          name: openbao-credentials
      path: kv      # Change this from just 'kv' to 'kv/data'
      server: http://10.43.39.227
      version: v1