{{- if (index .Values "gh-arc" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}  
  project: default
  source:
    chart: gha-runner-scale-set-controller
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.9.3
    helm:
      values: |
        flags:
          excludeLabelPropagationPrefixes:
            - "argocd.argoproj.io/instance"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}