{{- if (index .Values "gh-arc" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts/
    chart: gha-runner-scale-set-controller
    targetRevision: {{ (index .Values "gh-arc" "targetRevision") }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}