{{- if (index .Values "gh-arc" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: helm-charts/gha-runner-scale-set-controller
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        flags:
          excludeLabelPropagationPrefixes:
            - "argocd.argoproj.io/instance"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}