{{- if (index .Values "hpc-benchmarks" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc-hpc-benchmarks
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: helm-charts/gha-runner-scale-set
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        values: |
          githubConfigUrl: https://github.com/NCAR/hpc-benchmarks
          githubConfigSecret: ncote-gh-token
          controllerServiceAccount:
            namespace: arc-systems
            name: gh-arc-gha-rs-controller
        valueFiles: 
          - $sourceRepo/manifests/github/ncote-eso.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}