{{- if (index .Values "nickknows" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc-nickknows-scale-set
  namespace: argo
spec:
  destination:
    namespace: arc-systems
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: helm-charts/gha-runner-scale-set
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        values: |
          githubConfigUrl: https://github.com/Gin-G/NickKnows
          githubConfigSecret: nickknows-gh-token
          controllerServiceAccount:
            namespace: arc-systems
            name: gh-arc-gha-rs-controller
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/github/
      directory:
        include: "nickknows-eso.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Prune=true
{{- end }}