{{- if (index .Values "personadao" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc-personadao
  namespace: argo
spec:
  destination:
    namespace: personadao
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - path: helm-charts/gha-runner-scale-set
      repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      helm:
        values: |
          githubConfigUrl: https://github.com/ging/personadao
          githubConfigSecret: personadao-gh-token
          controllerServiceAccount:
            namespace: arc-systems
            name: gh-arc-gha-rs-controller
          maxRunners: 2
          minRunners: 0
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/github/
      directory:
        include: "peronadao-eso.yaml, personadao-secretstore.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
