{{- if (index .Values "backstage" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argo
spec:
  destination:
    namespace: backstage
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: {{ (index .Values "backstage" "targetRevision") }}
    helm:
      values: |
        ingress:
          enabled: true
          annotations: {
            traefik.ingress.kubernetes.io/router.entrypoints: web
          }
          host: backstage.gingmachine

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}