apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: NickCo7@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: NickCo7@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api
              key: cloudflare-api
              namespace: cert-manager 
