apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: cert-manager
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: OPENBAO_TOKEN
          name: openbao-credentials
      path: kv     # Change this from just 'kv' to 'kv/data'
      server: http://openbao.openbao.svc.cluster.local:8200
      version: v2