apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-arc
  namespace: gh-arc
roleRef:
  kind: Role
  name: actions-runner-controller
subjects:
- kind: ServiceAccount
  name: gh-arc-gha-rs-controller