apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ccpp-github-runner-token
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: ncote-ccpp-gh-token   # This matches your existing secret name for compatibility
  data:
  - secretKey: github_token    # This matches your existing secret key
    remoteRef:
      key: github               # Path in OpenBao where the secret is stored
      property: ncote-api-token   # The specific key you mentioned
