{{- if (index .Values "cert-manager" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: {{ (index .Values "cert-manager" "targetRevision") }}
      helm:
        values: |
          installCRDs: true
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
