{{- if (index .Values "external-secrets" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      helm:
        valueFiles: 
          - $sourceRepo/values/eso-values.yaml
        releaseName: external-secrets
      targetRevision: {{ (index .Values "external-secrets" "targetRevision") }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}