{{- if (index .Values "rook-ceph" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argo 
spec:
  project: default
  sources:
    - chart: rook-ceph
      repoURL: https://charts.rook.io/release
      targetRevision: {{ (index .Values "rook-ceph" "targetRevision") }}
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      path: manifests/rook-ceph
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}