{{- if (index .Values "traefik" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: {{ (index .Values "traefik" "targetRevision") }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
{{- end }}
