{{- if (index .Values "traefik" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      helm:
        valueFiles: 
          - $sourceRepo/values/traefik-values.yaml
        releaseName: traefik
      targetRevision: {{ (index .Values "traefik" "targetRevision") }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
{{- end }}
