{{- if (index .Values "argo-workflows" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
spec:
  destination:
    namespace: argo
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      helm:
        valueFiles: 
          - $sourceRepo/helm-charts/argo-workflows/values.yaml
        releaseName: argo-workflows
      targetRevision: 0.42.5
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}