{{- if (index .Values "external-secrets" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    helm:
      valueFiles: 
        - values.yaml
    path: helm-charts/external-secrets
    plugin:
      name: argocd-vault-plugin
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}