{{- if .Values.harbor.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argo
spec:
  destination:
    namespace: harbor
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: {{ (index .Values "harbor" "targetRevision") }}
      helm:
        valueFiles: 
          - $sourceRepo/values/harbor-values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}