{{- if (index .Values "lgtm" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm
  namespace: argo
spec:
  destination:
    namespace: lgtm
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: lgtm-distributed
      targetRevision: {{ (index .Values "lgtm" "targetRevision") }}
      helm:
        valueFiles: 
          - $sourceRepo/values/lgtm-values.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
