{{- if (index .Values "nvidia" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argo
spec:
  destination:
    namespace: nvidia
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://nvidia.github.io/k8s-device-plugin
      chart: nvidia-device-plugin
      targetRevision: {{ (index .Values "nvidia" "targetRevision") }}
      helm:
        values: |
          nodeSelector:
            gpu: "true"  # Use your existing node label
          priorityClassName: ""
          tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: {{ (index .Values "nvidia" "operatorRevision") }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
