{{- if (index .Values "nvidia" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argo
spec:
  destination:
    namespace: nvidia
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://nvidia.github.io/k8s-device-plugin
    chart: nvidia-device-plugin
    targetRevision: {{ (index .Values "nvidia" "targetRevision") }}
    helm:
      values: |
        deviceDiscoveryStrategy: "nvml"  # Make sure this is consistent
        nodeSelector:
          gpu: "true"
        priorityClassName: ""
        tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        config:
          plugin:
            nvidiaCTKPath: "/usr/bin/nvidia-ctk"
            containerDriverRoot: "/run/nvidia/driver"  # Add this if needed
        runtimeClassName: nvidia  # Add this line
    name: device-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
