{{- if (index .Values "openbao" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argo
spec:
  destination:
    namespace: openbao
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: {{ .Values.spec.source.repoURL }}
      path: helm-charts/openbao
      helm:
        valueFiles: 
          - secrets://https://raw.githubusercontent.com/NicholasCote/argo-k8s-stuff/values/openbao-values.yaml
      targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}