{{- if (index .Values "openbao" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argo
spec:
  destination:
    namespace: openbao
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      helm:
        valueFiles: 
          - $sourceRepo/values/openbao-values.yaml
        values: |
          server:
            ingress:
              hosts:
                - host: $kube:openbao/openbao-secret:openbao-host
        releaseName: openbao
      targetRevision: {{ (index .Values "openbao" "targetRevision") }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}