{{- if (index .Values "openbao" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argo
spec:
  destination:
    namespace: openbao
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: openbao-agent-injector-cfg    # include the specific resource name
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  project: default
  source:
    helm:
      valueFiles: 
        - openbao-values.yaml
        - secrets://openbao-values.enc.yaml
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: helm-charts/openbao
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}