{{- if (index .Values "openbao" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argo
spec:
  destination:
    namespace: openbao
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: openbao-agent-injector-cfg    # include the specific resource name
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      helm:
        valueFiles: 
          - $sourceRepo/values/openbao-values.yaml
        releaseName: openbao
        fileParameters:
          - name: server.ingress.hosts.host
            path: secrets+literal://vals!ref+vault://kv/openbao#/host?address=http:10.43.145.94:8200&
      targetRevision: {{ (index .Values "openbao" "targetRevision") }}
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: sourceRepo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}