{{- if (index .Values "rook-ceph" "enable") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argo 
spec:
  project: default
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: {{ (index .Values "rook-ceph" "targetRevision") }}
    helm:
      values: |
        crds:
          enabled: true
        operator:
          image:
            repository: rook/ceph
            tag: v1.12.9
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}