apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    ---
    - Infratructure:
        - Argo CD:
            href: https://argocd.nickknows.net
            description: GitOps Continuous Delivery
            icon: argocd.png
            widget:
              type: argocd
              url: https://argocd.nickknows.net
              key: {{HOMEPAGE_VAR_ARGOCD_TOKEN}}
    - Media:
        - Audiobookshelf:
            href: https://audiobookshelf.nickknows.net
            description: Audio Book Server
            icon: audiobookshelf.png
            widget:
              type: audiobookshelf
              url: https://audiobookshelf.nickknows.net
              key: {{HOMEPAGE_VAR_ABS_TOKEN}}
        - Immich:
            href: https://photos.nickknows.net
            description: Photo and Video Management
            icon: immich.png
            widget:
              type: immich
              url: https://photos.nickknows.net
              key: {{HOMEPAGE_VAR_IMMICH_TOKEN}}
              version: 2
        - Plex:
            href: http://192.168.4.45:32400/web
            description: Media Server
            icon: plex.png
            widget:
              type: plex
              url: http://192.168.4.45:32400
              key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
          
  kubernetes.yaml: |
    mode: cluster
    
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          label: "Cluster Overview"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

  bookmarks.yaml: |
    - Developer:
      - Github:
          - abbr: GH
            href: https://github.com/Gin-G
      - Website:
          - abbr: WS
            href: https://nickknows.net

    - Social:
        - Reddit:
            - icon: reddit.png
              href: https://www.reddit.com/user/nickco7/

    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://www.youtube.com/@Nick-Knows