apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.7

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: true
        passwordSecret:
          name: immich-db-credentials

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;

  storage:
    size: 10Gi
    storageClass: rook-ceph-block

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
