apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-media
  namespace: home-assistant
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
