apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-rolebinding
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: external-secrets  # Adjust if needed
roleRef:
  kind: ClusterRole
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io